### ISSUE TITLE
[Question]: JSONL format instead of JSON?

### ISSUE THREAD

**Issue by aleSuglia** [allenai/natural-instructions#273]
Hi there, 

This is a fantastic initiative. Thanks a lot for starting this!

I am eager to start contributing and I started looking at the dataset format. 

I started looking at the documentation and I realised that the default format is JSON. I was wondering why when it would be very cumbersome to load in memory the dataset every time. On the other hand, JSONL gives you the possibility to format each instance on each line and incrementally read them without storing them all in memory. I can see having in memory the entire set of tasks would be incredibly hard when the number of tasks will grow. 

I'd love to hear your thoughts on this. 

Cheers,
Alessandro

**Comment by danyaljj** [comment]
Hi @aleSuglia 👋  We chose JSON over JSONL because our task structure/scheme (as indicated in the main readme) is not quite flat. In particular, the instructions which define the task, are shared among all the instances. If we wanted to go with JSONL we could have repeated such common details at every line, which would result in a lot of necessary redundancy. 
Besides, our task files are not that large (So reading the whole task file at once is not an issue.)
