### ISSUE TITLE
Missing task numbers

### ISSUE THREAD

**Issue by swarooprm** [allenai/natural-instructions#482]
Let's update all the missing task numbers here, we can fill these numbers from the tasks in the latest PRs.
task063-064: https://github.com/allenai/natural-instructions-expansion/pull/474

**Comment by andersonjwan** [comment]
@swarooprm I created a small script to find which tasks are missing from the list. Unfortunately, it is a lot - 314 total. You can run the script below if you are curious yourself.

p.s. The script should be ran in the `tasks/` directory. I've also attached the list of missing task numbers instead of posting a comment to reduce spam [here](https://github.com/allenai/natural-instructions-expansion/files/7428008/missing-tasks.txt).

```python
if __name__ == "__main__":
    with open("README.md", "r", encoding="utf-8") as infile:
        comp = []
        line = infile.readline()

        while line:
            if line[0] == '`':
                task = (line.split("|")[0]).split("_")[0]
                number = task[5:] # get task number

                comp.append(int(number))

                if len(comp) == 2:
                    # do comparison
                    if (comp[1] - comp[0]) > 1:
                        for i in range((comp[1] - comp[0]) - 1):
                            print(f"Missing Task {comp[0] + i + 1}")

                    comp.pop(0)

            line = infile.readline()
```

**Comment by danyaljj** [comment]
Thanks @andersonjwan!
